/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Tracker API
 * Task Tracker API
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

export interface RegisterByLoginRequest {
  login: string;
  password: string;
}

export interface LoginRequest {
  login: string;
  password: string;
}

export interface UserResponse {
  id?: string;
  login?: string;
  registeredAt?: string;
}

export type RegisterByLogin200 = {
  success?: boolean;
  message?: string;
};

export type Login200 = {
  success?: boolean;
  message?: string;
};

/**
 * @summary Register by login
 */
export const registerByLogin = <TData = AxiosResponse<RegisterByLogin200>>(
  registerByLoginRequest: RegisterByLoginRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/auth/register-by-login`, registerByLoginRequest, options);
};

/**
 * @summary Login
 */
export const login = <TData = AxiosResponse<Login200>>(
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/auth/login`, loginRequest, options);
};

/**
 * @summary Me
 */
export const me = <TData = AxiosResponse<UserResponse>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/auth/me`, options);
};

export type RegisterByLoginResult = AxiosResponse<RegisterByLogin200>;
export type LoginResult = AxiosResponse<Login200>;
export type MeResult = AxiosResponse<UserResponse>;
