/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Task Tracker API
 * Task Tracker API
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export interface RegisterByLoginRequest {
  login: string;
  password: string;
}

export interface LoginRequest {
  login: string;
  password: string;
}

export type UserResponseUserInfo = {
  id?: string;
  login?: string;
  registeredAt?: string;
};

export interface UserResponse {
  success?: boolean;
  message?: string;
  status?: string;
  userInfo?: UserResponseUserInfo;
}

export interface BoardType {
  id: string;
  title: string;
  owner: string;
  ownerId: string;
  createdAt: string;
  updatedAt: string;
  userId: string;
}

export interface TaskType {
  id: string;
  title: string;
  description: string;
  order: number;
  columnId: string;
  createdAt: string;
  updatedAt: string;
  ownerId: string;
}

export interface ColumnType {
  id: string;
  title: string;
  order: number;
  boardId: string;
  ownerId: string;
  createdAt: string;
  updatedAt: string;
  isDeleted: boolean;
  creatorId: string;
  tasks: TaskType[];
}

export type BoardResponseResult = {
  board: BoardType;
  columns: ColumnType[];
};

export interface BoardResponse {
  status: string;
  message: string;
  result: BoardResponseResult;
}

export interface RenameTaskRequest {
  taskId: string;
  newTitle: string;
}

export type RegisterByLogin200 = {
  success?: boolean;
  message?: string;
};

export type Login200 = {
  success?: boolean;
  message?: string;
};

export type GetFullBoardParams = {
userId: string;
};

/**
 * @summary Register by login
 */
export const registerByLogin = <TData = AxiosResponse<RegisterByLogin200>>(
    registerByLoginRequest: RegisterByLoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/register-by-login`,
      registerByLoginRequest,options
    );
  }

/**
 * @summary Login
 */
export const login = <TData = AxiosResponse<Login200>>(
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/auth/login`,
      loginRequest,options
    );
  }

/**
 * @summary Me
 */
export const me = <TData = AxiosResponse<UserResponse>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/auth/me`,options
    );
  }

/**
 * @summary Get full board
 */
export const getFullBoard = <TData = AxiosResponse<BoardResponse>>(
    params: GetFullBoardParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/board/get-full-board`,undefined,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Rename task
 */
export const renameTask = <TData = AxiosResponse<BoardResponse>>(
    renameTaskRequest: RenameTaskRequest, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/board/task/rename`,
      renameTaskRequest,options
    );
  }

export type RegisterByLoginResult = AxiosResponse<RegisterByLogin200>
export type LoginResult = AxiosResponse<Login200>
export type MeResult = AxiosResponse<UserResponse>
export type GetFullBoardResult = AxiosResponse<BoardResponse>
export type RenameTaskResult = AxiosResponse<BoardResponse>
