openapi: 3.0.0
info:
  version: 1.0.0
  title: Task Tracker API
  description: Task Tracker API

servers:
  - url: /

paths:
  /auth/register-by-login:
    post:
      operationId: registerByLogin
      summary: Register by login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterByLoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /auth/login:
    post:
      operationId: login
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /auth/me:
    get:
      operationId: me
      summary: Me
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/UserResponse"
  /board/get-full-board:
    post:
      operationId: getFullBoard
      summary: Get full board
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/BoardResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
  /board/task/rename:
    post:
      operationId: renameTask
      summary: Rename task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RenameTaskRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/BoardResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
  /board/task/delete:
    delete:
      operationId: deleteTask
      summary: Delete task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteTaskRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/DeleteTaskResult"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
  /board/task/create:
    post:
      operationId: createTask
      summary: Create task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/BoardResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
  /board/task/update:
    patch:
      operationId: updateTask
      summary: Update task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTaskRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/TaskUpdateResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
  /board/column/create:
    post:
      operationId: createColumn
      summary: Create column
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateColumnRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/CreateColumnResult"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
components:
  schemas:
    RegisterByLoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
        password:
          type: string
    UserResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        status:
          type: string
        userInfo:
          type: object
          properties:
            id:
              type: string
            login:
              type: string
            registeredAt:
              type: string
    BoardType:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        owner:
          type: string
        ownerId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        userId:
          type: string
      required:
        - id
        - title
        - owner
        - ownerId
        - createdAt
        - updatedAt
        - userId
    TaskType:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        order:
          type: integer
        columnId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        ownerId:
          type: string
      required:
        - id
        - title
        - description
        - order
        - columnId
        - createdAt
        - updatedAt
        - ownerId
    ColumnType:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        order:
          type: integer
        boardId:
          type: string
        ownerId:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        isDeleted:
          type: boolean
        creatorId:
          type: string
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/TaskType"
      required:
        - id
        - title
        - order
        - boardId
        - ownerId
        - createdAt
        - updatedAt
        - isDeleted
        - creatorId
        - tasks
    BoardResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
        result:
          type: object
          properties:
            board:
              $ref: "#/components/schemas/BoardType"
            columns:
              type: array
              items:
                $ref: "#/components/schemas/ColumnType"
          required:
            - board
            - columns
      required:
        - status
        - message
        - result
    DeleteTaskRequest:
      type: object
      properties:
        taskId:
          type: string
      required:
        - taskId
    DeleteTaskResult:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
    RenameTaskRequest:
      type: object
      properties:
        taskId:
          type: string
        newTitle:
          type: string
      required:
        - taskId
        - newTitle
    CreateTaskRequest:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        columnId:
          type: string
        order:
          type: integer
        userId:
          type: string
      required:
        - title
        - description
        - columnId
        - userId
    UpdateTaskRequest:
      type: object
      properties:
        taskId:
          type: string
        title:
          type: string
        description:
          type: string
        order:
          type: integer
        columnId:
          type: string
        assigneeId:
          type: string
    TaskUpdateResponse:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
    CreateColumnRequest:
      type: object
      properties:
        title:
          type: string
        boardId:
          type: string
        order:
          type: integer
      required:
        - title
        - boardId
        - order
    CreateColumnResult:
      type: object
      properties:
        status:
          type: string
        message:
          type: string
      required:
        - status
        - message
