openapi: 3.0.0
info:
  version: 1.0.0
  title: Task Tracker API
  description: Task Tracker API

servers:
  - url: /api

paths:
  /auth/register-by-login:
    post:
      operationId: registerByLogin
      summary: Register by login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterByLoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /auth/login:
    post:
      operationId: login
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
  /auth/me:
    get:
      operationId: me
      summary: Me
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/UserResponse"
  /board/get-full-board:
    get:
      operationId: getFullBoard
      summary: Get full board
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/BoardResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/Error"

components:
  schemas:
    RegisterByLoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
        password:
          type: string
    LoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
        password:
          type: string
    UserResponse:
      type: object
      properties:
        id:
          type: string
        login:
          type: string
        registeredAt:
          type: string
    Board:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        ownerId:
          type: string
        createdAt:
          type: string
        userId:
          type: string
        updatedAt:
          type: string
    Column:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        order:
          type: number
        boardId:
          type: string
        ownerId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        isDeleted:
          type: boolean
        creatorId:
          type: string
        tasks:
          type: array
          items:
            $ref: "#/components/schemas/Task"
    Task:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        order:
          type: number
        description:
          type: string
        columnId:
          type: string
        ownerId:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    BoardResponse:
      type: object
      properties:
        board:
          type: object
          $ref: "#/components/schemas/Board"
        columns:
          type: array
          items:
            $ref: "#/components/schemas/Column"
    Error:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: number
        timestamp:
          type: string
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        statusCode:
          type: number
        timestamp:
          type: string
